### ISSUE TITLE
3.3 volts generation question

### ISSUE THREAD

**Issue by felmue** [m5stack/M5-CoreInk#1]
Hi guys

just curious - what is the reason for using SY7088 boost (bat -> 5volts) and SY8089 step down (5volts to 3.3volts) to power the ESP32 PICO chip instead of the AXP192 used in other products? I fear that will not allow for a very low current in deep sleep, but I might be wrong. I'd be interested about the current you measured in deep sleep - care to share that info?

Thank you very much in advance.

Best
Felix

**Comment by geiseri** [comment]
My understanding of the controller and code is that the entire system would power off, not really deep sleep.  The schematic is a bit vague but I think once the SY7088 is powered off it will remain that way until the power button is pressed again.  I think the intent from them is that you would use the ESP32 deep sleep and power off the eink display.   The APX was kind of overkill for these devices, so I think this will make life a bit easier in the end as long as the eink is truly powered off during the esp32 deep sleep it should be okay.  Really the only thing the AXP would buy us here is more insight into the battery.  Hope they can clear any of this up.

**Comment by felmue** [comment]
Hi @geiseri 

the nice thing with the AXP192 setup (as it is used for instance in the M5Core2 model) is that it directly converts battery voltage to 3.3 volts. The 5 volts generation is done via a separate IC which can be turned off. That saves a couple of mAs compared to the system used in M5Stack and now as it seem in the CoreInk model which always needs to boost up to 5 volts first to generate 3.3 volts. And 3.3 volts need to stay applied while ESP32 is in deep sleep.

I guess we'll find out when people get their CoreInk devices. I have one on order and plan to do some deep sleep measurements when it gets here.

Update: Looking at the M5Core2 schematic again I just realised that the RTC interrupt is connected to the AXP192 power key which means the RTC can turn on a fully shutdown system by timer or alarm. The CoreInk schematic is vague, but the sticker on the CoreInk shows the RTC is connected to something called MOS (power switch I guess) so hopefully we can do something similar here.

Thanks
Felix

**Comment by felmue** [comment]
Hi guys

I've received my M5CoreInk today and I think I now understand how the MOS (power switch) is supposed to work. The power on switch or RTC interrupt can turn M5CoreInk on, which then holds itself in the on state by setting GPIO12 high (done in M5.begin() function). The system can turn itself off by setting GPIO12 to low.

So my initial comment about how battery voltage is first boosted to 5 volts and then back down to 3.3 volts isn't that critical since a M5CoreInk most likely is in off state most of the time anyhow. (And ESP32 deep sleep / light sleep mode isn't really required for that.)

Thanks
Felix
