### ISSUE TITLE
void darwdate typo

### ISSUE THREAD

**Issue by Ajb2k3** [m5stack/M5-CoreInk#14]
Line 32 
void darwDate( RTC_DateTypeDef *date)

should be
void drawDate( RTC_DateTypeDef *date)

**Comment by TinyuZhao** [comment]
Thank you for your feedback, we have [fixed](https://github.com/m5stack/M5-CoreInk/commit/4e7caaa099c474af3a8807e7acb0037fd57a26db) this issue, please try pulling the latest library.
