### ISSUE TITLE
getBatVoltage seems to be missing a free

### ISSUE THREAD

**Issue by phoddie** [m5stack/M5-CoreInk#15]
It looks like the memory allocated by this function will be orphaned.

https://github.com/m5stack/M5-CoreInk/blob/b5003a1661bb55c48a0c1d1aa2b191e6e2bb00ca/examples/FactoryTest/FactoryTest.ino#L52-L61

**Comment by TinyuZhao** [comment]
We have now [solved](https://github.com/m5stack/M5-CoreInk/commit/79d34ae692b237041d1b302ebac9978300750512) this problem, thank you for your feedback

**Comment by phoddie** [comment]
Great. Thank you!
