### ISSUE TITLE
M5CoreInk::shutdown(const RTC_TimeTypeDef &) not work

### ISSUE THREAD

**Issue by thorv** [m5stack/M5-CoreInk#19]
when sleep with shutdown(RTC_TimeTypeDef), it not wake up at the time.

I tried
```
int RTC::SetAlarmIRQ(const RTC_TimeTypeDef &RTC_TimeStruct)
{
    uint8_t irq_enable = false;
    uint8_t out_buf[4] = {0x80, 0x80, 0x80, 0x80};

[snip]

    //out_buf[2] = 0x00; //remove
    //out_buf[3] = 0x00; //remove

    uint8_t reg_value = ReadReg(0x01);
```
it worked. 
out_buf[2], outbuf[3] should be invalid number as a date/dayofweek, I think.

**Comment by TinyuZhao** [comment]
Fixed.https://github.com/m5stack/M5Core-Ink/commit/8276d8b95ac75a115f0b542f3a47621d494d61b7

Thank you for your help!
