### ISSUE TITLE
RTC_WakeUp example error

### ISSUE THREAD

**Issue by roberto1963** [m5stack/M5-CoreInk#2]
Hello, 
When I try to compile RTC_WakeUp.ino code from examples in Arduino IDE , I got this 
error: 'class M5CoreInk' has no member named 'shutdown'

What can I do ?
Best regards.
Roberto

**Comment by felmue** [comment]
Hello @roberto1963 

I think there were some last minute changes. Could you try with the latest sources from github? I don't have an issue compiling and running the RTC_WakeUp.ino on my M5CoreInk.

Thanks
Felix

**Comment by roberto1963** [comment]
Hello Felix, 
 
It seems that the library for M5 CoreInk is not updated for the library manager of arduino IDE .
 
RTC_WakeUp example is on Github but not in arduino library that I downloaded with the library manager last week .
In addition, library manager don't give the possibility to update the CoreInk library ... So I guess there is a version problem ?
How can I get the last version of CoreInk library ?
 
Thanks
Roberto
 
 
> Message du 28/11/20 15:47> De : "felmue" > A : "m5stack/M5-CoreInk" > Copie à : "roberto1963" , "Mention" > Objet : Re: [m5stack/M5-CoreInk] RTC_WakeUp example error (#2)> >
>
> Hello @roberto1963
> I think there were some last minute changes. Could you try with the latest sources from github? I don't have an issue compiling and running the RTC_WakeUp.ino on my M5CoreInk.
> Thanks> Felix
—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/m5stack/M5-CoreInk/issues/2#issuecomment-735239738", "url": "https://github.com/m5stack/M5-CoreInk/issues/2#issuecomment-735239738", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by felmue** [comment]
Hi Roberto

I am sorry, but I don't know how often the Arduino libraries are updated with a fresh copy from github. What I do in such a situation is to download the zip file from github directly and copy the unzipped content into the correct location manually. 

Thanks
Felix
