### ISSUE TITLE
Limited fonts available in arduino api for coreink

### ISSUE THREAD

**Issue by linxcow** [m5stack/M5-CoreInk#20]
I'd like to have some more fonts than the standard 2 fonts in the api.

- Ascii8x16.cpp
- Ascii24x48.cpp

Can someone add some bold fonts to the library?

**Comment by TinyuZhao** [comment]
You might try contacting this person who provided the word molds

https://github.com/lovyan03/LovyanGFX/blob/19a2e711e70a5a072d5463be6c09c06204a35835/src/lgfx/Fonts/Ascii24x48.h#L4

<img width="688" alt="image" src="https://github.com/m5stack/M5Core-Ink/assets/44396641/badac5a0-2386-4645-a02d-0fda66307e26">
