### ISSUE TITLE
Serial does not work

### ISSUE THREAD

**Issue by stephankoelle** [m5stack/M5-CoreInk#24]
### Describe the bug

When using any example serial does not print any out.

### To reproduce

```
void setup() {
  M5.begin();
  while (!Serial);
  Serial.printf("this will not be printed\n");
}
```

### Expected behavior

Serial should always work.

when I remove remove
`pinMode(1, OUTPUT);`
from M5CoreInk.cpp it works, what should the line do?

Its also important to know, that serial is inited with: 115200, that was unexpected.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Core-Ink/issues?q=)
- [X] My report contains all necessary details

**Comment by TinyuZhao** [comment]
It works very well, please try to upgrade the warehouse used, and use the correct board.
<img width="1282" alt="image" src="https://github.com/m5stack/M5Core-Ink/assets/44396641/ceae90c2-08a1-4cd5-8fa4-496f4e59166b">

**Comment by stephankoelle** [comment]
New Platfromio Project:
with:
```
[env:m5stack-coreink]
platform = espressif32
board = m5stack-coreink
framework = arduino
monitor_speed = 115200
lib_deps= m5stack/M5GFX@^0.1.16, m5stack/M5Core-Ink@^1.0.0 
```
  
code from:
https://github.com/m5stack/M5Core-Ink/blob/master/examples/Basics/Button/Button.ino
  
<img width="1440" alt="Screenshot 2024-06-12 at 11 34 20" src="https://github.com/m5stack/M5Core-Ink/assets/3218709/ecaa6dfc-f87b-45e3-bdea-1ab9038c4aeb">
=> serial after reset: no
  
 ------
 
remove the line:  
`pinMode(1, OUTPUT);`
  
<img width="1440" alt="Screenshot 2024-06-12 at 11 42 40" src="https://github.com/m5stack/M5Core-Ink/assets/3218709/223bbd43-165b-49c5-80bb-272befb41f8b">
=> serial after reset: yes
  
  
Here is one other person having a similar problem:
[https://forum.arduino.cc/t/serial-print-not-working-correctly-with-m5stack-coreink/1184227](url)


The demo app itself work on the device.

**Comment by TinyuZhao** [comment]
Using the coreink library on the master branch on GitHub, using your INI file, test the button example.
<img width="1389" alt="image" src="https://github.com/m5stack/M5Core-Ink/assets/44396641/2d18fb0a-c5c4-427a-b74c-b8230aeb1c5a">

**Comment by stephankoelle** [comment]
What could be the difference? Maybe here?
```
PLATFORM: Espressif 32 (6.7.0) > M5Stack-Core Ink
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.20016.0 (2.0.16) 
 - tool-esptoolpy @ 1.40501.0 (4.5.1) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
```

**Comment by TinyuZhao** [comment]
Try cloning the coreink repository into the lib in platformio.

```cpp
Processing M5CoreInk (platform: espressif32; board: m5stack-coreink; framework: arduino)
----------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/m5stack-coreink.html
PLATFORM: Espressif 32 (6.6.0) > M5Stack-Core Ink
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.20014.231204 (2.0.14) 
 - tool-esptoolpy @ 1.40501.0 (4.5.1) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 125 compatible libraries
Scanning dependencies...
^CBuild interrupted.
AbortedByUser: Aborted by user

 *  终端进程“platformio 'run', '--environment', 'M5CoreInk'”已终止，退出代码: 1。 
 *  终端将被任务重用，按任意键关闭。 

 *  正在执行任务: platformio run --environment M5CoreInk 

Processing M5CoreInk (platform: espressif32; board: m5stack-coreink; framework: arduino)
----------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/m5stack-coreink.html
PLATFORM: Espressif 32 (6.6.0) > M5Stack-Core Ink
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.20014.231204 (2.0.14) 
 - tool-esptoolpy @ 1.40501.0 (4.5.1) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 125 compatible libraries
```

**Comment by stephankoelle** [comment]
could you try with the 1.0.0 release core-ink lib? like:
`lib_deps= m5stack/M5GFX@^0.1.16, m5stack/M5Core-Ink@^1.0.0
`
I have seen there are some commits after: M5Core-Ink@^1.0.0 release.  Maybe the current version should be tagged as release?

**Comment by stephankoelle** [comment]
I have switched to master, no change for me ther

**Comment by TinyuZhao** [comment]
I want to ask what model your computer is, is it from the Apple M3 chip series?
If you still have the packaging, could you provide me with the SN code on the packaging.

eg:
![10241718330352_ pic](https://github.com/m5stack/M5Core-Ink/assets/44396641/b59f088c-a8aa-4639-9893-933548c7d79d)

**Comment by TinyuZhao** [comment]
The problem has been identified, this issue will occur after Espressif 32 (6.6.0) version, it will not occur in 6.6.0 and below, I will fix it.
